apiVersion: v1
description: Helm chart for deploying Istio operator
icon: https://istio.io/favicons/android-192x192.png
keywords:
- istio
- operator
name: istio-operator
sources:
- http://github.com/istio/istio/operator
version: 1.6.0
