{{- if .Values.global.meshExpansion.enabled }}
{{ $root := . }}
{{- range .Values.gateways }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: meshexpansion-gateway
  namespace: {{ $root.Release.Namespace }}
  labels:
    release: {{ $root.Release.Name }}
spec:
  selector:
    istio: {{ .selector | default "ingressgateway" }}
  servers:
    - port:
        number: 15012
        protocol: TCP
        name: tcp-istiod
      hosts:
        - "*"
    - port:
        number: 15017
        protocol: TCP
        name: tcp-istiodwebhook
      hosts:
        - "*"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshexpansion-vs-istiod
  namespace: {{ $root.Release.Namespace }}
  labels:
    release: {{ $root.Release.Name }}
spec:
  hosts:
  - istiod.{{ .Values.global.istioNamespace }}.svc.{{ .Values.global.proxy.clusterDomain }}
  gateways:
  - meshexpansion-gateway
  tcp:
  - match:
    - port: 15012
    route:
    - destination:
        host: istiod.{{ .Values.global.istioNamespace }}.svc.{{ .Values.global.proxy.clusterDomain }}
        port:
          number: 15012
  - match:
    - port: 15017
    route:
    - destination:
        host: istiod.{{ $root.Release.Namespace }}.svc.{{ .Values.global.proxy.clusterDomain }}
        port:
          number: 443
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: meshexpansion-dr-istiod
  namespace: {{ $root.Release.Namespace }}
  labels:
    release: {{ $root.Release.Name }}
spec:
  host: istiod.{{ $root.Release.Namespace }}.svc.{{ .Values.global.proxy.clusterDomain }}
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 15012
      tls:
        mode: DISABLE
    - port:
        number: 15017
      tls:
        mode: DISABLE

{{- end }}
