{{- if .Values.global.multiCluster.enabled }}
{{ $root := . }}
{{- range .Values.gateways }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-multicluster-ingressgateway
  namespace: {{ .namespace | default $root.Release.Namespace }}
  labels:
{{ .labels | toYaml | indent 4 }}
    release: {{ $root.Release.Name }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*.{{ $root.Values.global.multiCluster.globalDomainSuffix | trim }}"
    port:
      name: tls
      number: 15443
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH
---
{{- if $root.Values.global.multiCluster.includeEnvoyFilter }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-multicluster-ingressgateway
  namespace: {{ .namespace | default $root.Release.Namespace }}
  labels:
{{ .labels | toYaml | indent 4 }}
    release: {{ $root.Release.Name }}
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 15443
        filterChain:
          filter:
            name: "envoy.filters.network.sni_cluster"
    patch:
      operation: INSERT_AFTER
      value:
        name: "envoy.filters.network.tcp_cluster_rewrite"
        typed_config:
          "@type": "type.googleapis.com/istio.envoy.config.filter.network.tcp_cluster_rewrite.v2alpha1.TcpClusterRewrite"
          cluster_pattern: "\\.{{ $root.Values.global.multiCluster.globalDomainSuffix | trim }}$"
          cluster_replacement: ".svc.{{ $root.Values.global.proxy.clusterDomain }}"
---
{{- end }}
## To ensure all traffic to globalDomainSuffix is using mTLS
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-multicluster-ingressgateway
  namespace: {{ .namespace | default $root.Release.Namespace }}
  labels:
{{ .labels | toYaml | indent 4 }}
    release: {{ $root.Release.Name }}
spec:
  host: "*.{{ $root.Values.global.multiCluster.globalDomainSuffix | trim }}"
  {{- if $root.Values.global.defaultConfigVisibilitySettings }}
  exportTo:
  - '*'
  {{- end }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
{{- end }}
{{- end }}
