{{- range $name, $options:= .Values.gateways }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}-sds
  namespace: {{ $options.namespace | default $.Release.Namespace }}
  labels:
    release: {{ $.Release.Name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
{{- end }}
