{{- range $name, $options:= .Values.deployments }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}-sds
  namespace: {{ $options.namespace | default $.Release.Namespace }}
  labels:
    release: {{ $.Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}-sds
subjects:
- kind: ServiceAccount
  name: {{ $name }}-service-account
{{- end }}
