{{ $root := . }}
{{- range .Values.gateways }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}-sds
  namespace: {{ .namespace | default $root.Release.Namespace }}
  labels:
    release: {{ $root.Release.Name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
{{- end }}
