{{ $root := . }}
{{- range .Values.gateways }}
---
apiVersion: v1
kind: ServiceAccount
{{- if $root.Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range $root.Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: {{ .name }}-service-account
  namespace: {{ .namespace | default $root.Release.Namespace }}
  labels:
{{ .labels | toYaml | trim | indent 4 }}
    release: {{ $root.Release.Name }}
{{- end }}
