apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: cray-istio
spec:
  profile: minimal
  hub: {{ .Values.hub }}
  tag: {{ .Values.tag }}
  meshConfig:
{{ toYaml .Values.meshConfig | indent 6 }}
  components:
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            {{- if .Values.pilot.resources.requests.cpu }}
            cpu: {{ .Values.pilot.resources.requests.cpu }}
            {{- end }}
            {{- if .Values.pilot.resources.requests.memory }}
            memory: {{ .Values.pilot.resources.requests.memory }}
            {{- end }}
      hub: {{ .Values.pilot.hub }}
      tag: {{ .Values.pilot.tag }}
  addonComponents:
    prometheus:
{{ toYaml .Values.addonComponents.prometheus | indent 6 }}
    kiali:
      enabled: true
    tracing:
      enabled: true
  values:
    global:
{{ toYaml .Values.istio.global | indent 6 }}
    kiali:
{{ toYaml .Values.istio.kiali | indent 6 }}
    prometheus:
{{ toYaml .Values.istio.prometheus | indent 6 }}
    grafana:
{{ toYaml .Values.istio.grafana | indent 6 }}
