#
# MIT License
#
# (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v2
version: 1.0.0
name: cray-istio-pilot
description: Helm chart for deploying Istio control plane (istiod)
keywords:
  - istio
  - pilot
  - istiod
home: https://github.com/Cray-HPE/cray-istio
sources:
  - https://github.com/Cray-HPE/cray-istio
dependencies:
  - name: istiod
    version: 1.26.0
    repository: https://istio-release.storage.googleapis.com/charts
maintainers:
  - name: arka-pramanik-hpe
appVersion: 1.26.0
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: istio-pilot-distro
      image: artifactory.algol60.net/csm-docker/stable/istio/pilot:1.26.0-cray1-distroless
    - name: istio-pilot-distroless
      image: artifactory.algol60.net/csm-docker/stable/istio/pilot:1.26.0-cray1
    - name: istio-proxy-distro
      image: artifactory.algol60.net/csm-docker/stable/istio/proxyv2:1.26.0-cray1-distroless
    - name: istio-proxy-distroless
      image: artifactory.algol60.net/csm-docker/stable/istio/proxyv2:1.26.0-cray1
