#
# MIT License
#
# (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
istiod:
  global:
    configValidation: true
    hub: artifactory.algol60.net/csm-docker/stable/istio
    imagePullPolicy: IfNotPresent
    istioNamespace: istio-system
    priorityClassName: csm-high-priority-service
    tag: 1.25.2-cray1-distroless

  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      tracing:
        zipkin:
          address: zipkin.istio-system.svc.cluster.local:9411

  image: pilot
  hub: artifactory.algol60.net/csm-docker/stable/istio
  tag: 1.25.2-cray1-distroless

  cni:
    enabled: false
  ztunnel:
    resourceName: ztunnel

  replicaCount: 3
  autoscaleMin: 3
  autoscaleMax: 8
  env:
    ENABLE_LEGACY_FSGROUP_INJECTION: false
    JWT_POLICY: third-party-jwt
    USE_ISTIO_JWT_FILTER: "true"
    PILOT_ENABLE_UNSAFE_REGEX: "true"
