apiVersion: v2
appVersion: 1.7.8
name: cray-istio
description: Cray Istio for cluster service mesh including service gateway/sidecars, monitoring etc.
home: "cloud/cray-charts"
version: 1.26.0
dependencies:
  - name: ingressgatewayhmn
    version: 1.1.0
  - name: istio
    version: 1.1.0
