apiVersion: v2
version: 1.23.1
name: cray-istio-operator
description: Helm chart for deploying Istio operator
keywords:
  - istio
  - operator
home: https://github.com/Cray-HPE/cray-istio
sources:
  - https://github.com/Cray-HPE/cray-istio
dependencies:
  - name: istio-operator
    version: 1.7.0
maintainers:
  - name: brantk-hpe
appVersion: 1.8.6
annotations:
  artifacthub.io/license: MIT
